### ISSUE TITLE
META: GnoSwap

### ISSUE THREAD

**Issue by dongwon8247** [gnolang/hackerspace#49]
# Overview
GnoSwap is the first Concentrated Liquidity AMM DEX developed with [Gnolang](https://gno.land/gnolang), inspired by Uniswap V3—the most advanced and battle-tested AMM. Its goal is to bring censorship-resistant, non-custodial, and secure financial infrastructure to Gnoland, establishing the most capital-efficient liquidity layer within the Gnoland ecosystem.

GnoSwap is entirely permissionless, allowing any GRC20 token realms to be added and traded as soon as they're deployed to the GnoVM, without requiring any registry approval.

### URLs
- Realms (contract): https://github.com/gnoswap-labs/gnoswap
- Interface: https://github.com/gnoswap-labs/gnoswap-interface
- Docs: https://docs.gnoswap.io/
- Blog: https://medium.com/@gnoswaplabs
- Twitter: https://twitter.com/gnoswaplabs

# Key Features
- **Swap:** Supporting swaps for any token on Gno.land including GRC20s, native tokens, and IBC-transferred tokens. The SwapRouter ensures that every swap receives the best possible pricing.
- **Create Liquidity Positions:** Abstracting the complexities involved in Concentrated Liquidity to provide a simple, intuitive experience for liquidity providers while offering full customizability.
- **Stake Position:** Offering the Warm-up Period, a novel staking mechanism designed to incentivize long-term liquidity provision while offering flexibility for those who frequently need to adjust their price range to stay active due to liquidity concentration.
- **Incentivize Pool:** Providing a tool that incentives extra rewards, which can be added to bootstrap liquidity in pools.
- **Wallet:** Viewing all of your assets at a glance with real-time updates on liquidity provision and staking. Support for IBC transfers will be available in the future.
- **Dashboard:** Analyzing platform metrics and on-chain activities within GnoSwap.
- **(Upcoming) Governance:** Providing governance tools for xGNS holders who make key decisions for the platform.
- **(Upcoming) Launchpad:** Offering a tool to facilitate the launch of crypto projects within the Gnoland ecosystem.
- **(Upcoming) Perpetual Trading:** Offering perpetual trading leverage.

# Milestones
- [ ] GnoSwap Closed Beta Launch //Q4 2023
- [ ] GnoSwap Open Beta Launch //Q1 2024
- [ ] GnoSwap Mainnet Launch //Q2 2024
- [ ] Launchpad Platform Launch //Q3 2024
- [ ] Multi-chain Support Enabled //Q4 2024
- [ ] Customizable Perpetual DEX Launch //H1 2025

**Comment by adr-sk** [comment]
## Gnoswap Beta Testing Guide
Gnoswap Beta Website: https://beta.gnoswap.io/

### Task 1. Connect Your Wallet
You'll need a wallet to interact with Gnoswap. [Download Adena](https://chromewebstore.google.com/detail/adena/oefglhbffgfkcpboeackfgdagmlnihnh) from the Chrome Webstore. Create or restore your wallet and change the network to Gnoswap-Testnet in the Settings. Once your wallet is set up, visit Gnoswap Beta, and connect by clicking on Wallet Login in the header.

> Note: You won't be able to check your transaction history and balance for `Gnoswap-Testnet` in Adena Wallet and Gnoscan, as they will only support official Gno testnets and the mainnet. However, you can check your balance and recent transactions via Gnoswap's Wallet Menu and the Notifications feature.

### Task 2. Get Tokens From the Faucet
Click on the Faucet button on the right side of the header to receive testnet tokens you can use on Gnoswap.

### Task 3. Add Liquidity
You can add liquidity to liquidity pools from which the traders will swap from. In return, you will receive a portion of swap fees as a reward.

1.  In the Earn Menu, click on New Position.
2.  Select the pair of tokens for the pool in which you will add liquidity.
3.  Select the Fee Tier and the Price Range. If you're the first person to add liquidity, you will first need to create the pool and manually select the starting price.
4.  Enter the amount of tokens to add, and approve the transaction in Adena.
5.  Your newly added position will be available under My Positions in the Earn Menu.

### Task 4. Swap Tokens
You can swap tokens against the liquidity of existing liquidity pools. Gnoswap will automatically route your swap to the optimal path that calculates the best pricing.  

1.  In the Swap Menu, select the tokens you will swap.
2.  Enter the number of tokens to swap. You can specify either the input or the output to sell or receive the exact amount of tokens you want.
3.  Review the details of the swap such as the price impact, fees, and the route under the expandable area.
4.  Click on Swap and approve the transaction in Adena.

### Task 5. Stake Positions
By staking, you are locking your positions in return for extra rewards you will receive in the form of $GNS emissions or external incentives provided to each pool.

1.  In the Earn Menu, click on Stake Position.
2.  Select the positions you wish to stake.
3.  Review the details and click on Stake Position to confirm the transaction in Adena.
4.  Your staked positions will be highlighted under My Positions in the Earn Menu.

### Task 6. Claim Rewards
You can claim all Claimable Rewards at once by clicking on the Claim All button in the Wallet menu, or individually collect by each pool by clicking on the Claim All button in the Pool Details page. This will transfer your rewards from the contract to your wallet.

### Task 7. Add Incentives
You may add external incentives to existing pools. This will increase the rewards from specific pools to incentivize liquidity providers.  

1.  In the Earn Menu, click on Incentivize Pool.
2.  Select the pool to add incentives to, the distribution period, and the reward amount. Your tokens will be linearly distributed throughout the period.
3.  Click on Incentivize Pool and approve the transaction on Adena.

## Feedback

If you encounter a bug or come up with an improvement suggestion during your test, please share it in the comments below or you can submit your feedback via [Google form](https://forms.gle/bFS8vdYGzHNNZ9f2A).

**Comment by r3v4s** [comment]
# Gnoswap Contract
- [Repo](https://github.com/gnoswap-labs/gnoswap)
- [Docs](https://docs.gnoswap.io/)
- [UML](https://drive.google.com/file/d/1gXjsYZNVfZDqG54jOjaZOvKDeKODe7IR/view?usp=sharing)

**Comment by dongwon8247** [comment]
# GnoSwap Contract Overview

- GitHub Repository ([Link](https://github.com/gnoswap-labs/gnoswap)): Open-sourced contracts of GnoSwap.
- Documentation ([Link](https://docs.gnoswap.io/contracts/pool/pool.gno)): Documentation of core contracts.
- UML diagram
![Gnoswap_UML](https://github.com/gnolang/hackerspace/assets/74406335/782ed1a1-119d-4a6a-9657-7af40c8b5f2c)
